### ISSUE TITLE
Revisions for scenery input event recording/playback in Sim.js

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#301]
To proceed with https://github.com/phetsims/together/issues/68 @jonathanolson and @samreid discussed updates to Joist to support scenery input event recording and playback using phet-io.  I've got input event recording and playback working in my working copy, which has also got Sim.js from 900 LOC down to 750 LOC, a significant improvement, see #208 

I have also simplified SIm's usage of request animation frame, creating a function as a Sim property rather than an inner-closure function and providing methods that both normal mode and playback mode can use.

Testing my working copy changes before committing:
- I have tested record & playback in Concentration, and all seems well.
- I tested acid base solutions in requirejs mode in chrome and all seems well.
- Scenery qunit shows: 4618 assertions of 4618 passed, 0 failed.
- "eslint:allFiles" from function-builder is succeeding
- So far 21/21 sims have passed the fuzz tester, more are proceeding.  I don't expect to find any sim-specific issues since the changes here have been fairly isolated in Joist.

I'll let the fuzz tester continue a bit but wanted to report my progress here. More work remains regarding connectivity between together and Sim.js for recording/playback but this is a good checkpoint so I wanted to check in too.  If the fuzz tester seems good I'll commit afterwards.

The reason I've created an issue for this and detailed my testing is that Sim.js is widely used in simulation code, and the changes here are important and nontrivial.

**Comment by samreid** [comment]
Recording my testing progress:

![image](https://cloud.githubusercontent.com/assets/679486/10446236/9aef647a-7139-11e5-9efc-0bfa95acbc45.png)

```
least-squares-regression
Uncaught Error: Assertion failed: Segment end is infinite
Error: Assertion failed: Segment end is infinite
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Subpath.inherit.addSegmentDirectly (http://localhost:8080/kite/js/util/Subpath.js?bust=1444714058755:104:17)
    at http://localhost:8080/kite/js/util/Subpath.js?bust=1444714058755:120:17
    at Function.St (http://localhost:8080/sherpa/lib/lodash-2.4.1.min.js?bust=1444714058755:23:149)
    at Subpath.inherit.addSegment (http://localhost:8080/kite/js/util/Subpath.js?bust=1444714058755:119:9)
    at Shape.inherit.addSegmentAndBounds (http://localhost:8080/kite/js/Shape.js?bust=1444714058755:784:29)
    at Shape.inherit.lineToPoint (http://localhost:8080/kite/js/Shape.js?bust=1444714058755:146:14)
    at Shape.inherit.lineTo (http://localhost:8080/kite/js/Shape.js?bust=1444714058755:136:44)
    at HSlider.inherit.addTick (http://localhost:8080/sun/js/HSlider.js?bust=1444714058755:262:12)
    at new VerticalSlider (http://localhost:8080/least-squares-regression/js/least-squares-regression/view/MyLineControlPanel.js?bust=1444714058755:61:16)
pendulum-lab
Uncaught Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at new NavigationBar (http://localhost:8080/joist/js/NavigationBar.js?bust=1444714311699:73:19)
    at new Sim (http://localhost:8080/joist/js/Sim.js?bust=1444714311699:369:25)
    at http://localhost:8080/pendulum-lab/js/pendulum-lab-main.js?bust=1444714311699:41:15
    at doneLoadingImages (http://localhost:8080/joist/js/SimLauncher.js?bust=1444714311699:33:9)
    at Object.launch (http://localhost:8080/joist/js/SimLauncher.js?bust=1444714311699:53:9)
    at http://localhost:8080/pendulum-lab/js/pendulum-lab-main.js?bust=1444714311699:40:15
    at Object.context.execCb (http://localhost:8080/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://localhost:8080/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://localhost:8080/sherpa/lib/require-2.1.11.js:1113:20)
```

I'll try to wrap this up tomorrow before I commit the changes described above.

**Comment by samreid** [comment]
Sim fuzz tests complete and no problems look related to the Sim.js changes.  I'm also pleasantly surprised at the fact that only 4 sims are failing fuzz tests.

![image](https://cloud.githubusercontent.com/assets/679486/10458035/19c625a8-7186-11e5-969a-6b0573cfc7cf.png)

```
rutherford-scattering
Uncaught Error: Assertion failed: undefined
Error: Assertion failed: undefined
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Node.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1444746194717:2343:17)
    at http://localhost:8080/sun/js/ToggleNode.js?bust=1444746194717:44:22
    at Property.inherit.link (http://localhost:8080/axon/js/Property.js?bust=1444746194717:171:11)
    at new ToggleNode (http://localhost:8080/sun/js/ToggleNode.js?bust=1444746194717:43:21)
    at PlayPauseButton.BooleanRoundToggleButton [as constructor] (http://localhost:8080/sun/js/buttons/BooleanRoundToggleButton.js?bust=1444746194717:22:86)
    at new PlayPauseButton (http://localhost:8080/scenery-phet/js/buttons/PlayPauseButton.js?bust=1444746194717:61:30)
    at new AnimationControlView (http://localhost:8080/rutherford-scattering/js/rutherford-atom/view/AnimationControlView.js?bust=1444746194717:29:27)
    at new RutherfordAtomView (http://localhost:8080/rutherford-scattering/js/rutherford-atom/view/RutherfordAtomView.js?bust=1444746194717:56:20)
    at RutherfordAtomScreen.Screen.call.backgroundColor [as createView] (http://localhost:8080/rutherford-scattering/js/rutherford-atom/RutherfordAtomScreen.js?bust=1444746194717:34:34)
vibe
Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
    at TypeError (native)
    at Sound.play (http://localhost:8080/vibe/js/Sound.js?bust=1444746504349:148:31)
    at VibeScreenView.RectangularPushButton.listener (http://localhost:8080/vibe/js/vibe/view/VibeScreenView.js?bust=1444746504349:53:24)
    at http://localhost:8080/sun/js/buttons/PushButtonModel.js?bust=1444746504349:126:9
    at Array.forEach (native)
    at PushButtonModel.inherit.fire (http://localhost:8080/sun/js/buttons/PushButtonModel.js?bust=1444746504349:125:12)
    at http://localhost:8080/sun/js/buttons/PushButtonModel.js?bust=1444746504349:72:25
    at Array.onValueObserver (http://localhost:8080/axon/js/Property.js?bust=1444746504349:295:13)
    at Property.inherit._notifyObservers (http://localhost:8080/axon/js/Property.js?bust=1444746504349:111:29)
    at Property.inherit._setAndNotifyObservers (http://localhost:8080/axon/js/Property.js?bust=1444746504349:97:14)
```

**Comment by samreid** [comment]
Based on the promising results of the above testing, I'm going to commit my changes.  But I'll also create a new issue label "needs-review-before-publication" since these changes should really be reviewed before any simulations are published with the changes.

**Comment by samreid** [comment]
Changes committed to 3 repos above, I'll mark this issue as described above.

**Comment by samreid** [comment]
I'll also mark for developer-meeting to make others aware of this work and discuss scheduling a reviewer.

**Comment by samreid** [comment]
@jonathanolson suggests that review is not necessary before republication--any issues will be caught during testing.

**Comment by samreid** [comment]
@pixelzoom asked:

> Looks like significant changes. Is this work done? (The issue is still open.) Has it been tested? 

Regarding Sim.js, here is the testing I completed for it with no problems observed:

    I have tested record & playback in Concentration, and all seems well.
    I tested acid base solutions in requirejs mode in chrome and all seems well.
    Scenery qunit shows: 4618 assertions of 4618 passed, 0 failed.
    "eslint:allFiles" from function-builder is succeeding
    Completed Fuzz Testing on all simulations
    Molarity (current build of master) looks good on iPad3/iOS9
    Molarity (current build of master) looks good on OS X El Capitan Chrome 46.0.2490.71 (64-bit)
    Molarity (current build of master) looks good on OS X El Capitan Firefox 40.0.3
    Molarity (current build of master) looks good on OS X El Capitan Safari 9.0.1
    Bending Light (current build of master) looks good

Since it is a significant change to a core class I have recommended a code review for the changes, but the consensus at yesterday's meeting is that it does not need to be code reviewed before we RC Test or publish any simulations.  There will be more changes in the future when I resume work on scenery input event recording or other aspects of Joist.

**Comment by samreid** [comment]
My work on this is complete for now.  @jonathanolson do you want to review?

**Comment by pixelzoom** [comment]
Reviewing issue status... Looks like work is complete, waiting for @jonathanolson to review.  

@ jonathanolson Do you have time to take a look?

**Comment by jonathanolson** [comment]
Will review.

**Comment by pixelzoom** [comment]
This has been ready-for-review for quite awhile, would be nice to wrap up.

**Comment by jonathanolson** [comment]
The file joist/js/PlaybackSim doesn't seem to be used by anything?

Changes look fine.

Currently, input events are turned into a string form meant for eval. I'd highly prefer this change to something like a JSON format that can be fed back in for playback.

Thoughts, and can we remove PlaybackSim?

**Comment by samreid** [comment]
@zepumph can you check if PlaybackSim can be deleted?  I can't see any usages of it in master.

**Comment by samreid** [comment]
Yes, let's convert input events from eval to JSON.  Perhaps a new issue in scenery?

**Comment by zepumph** [comment]
I deleted `PlaybackSim.js`, looks like the last commit on it was in 2015. @samreid I don't see another issue in scenery, or tagged in this issue. Back to you.

**Comment by samreid** [comment]
Thanks, I created https://github.com/phetsims/scenery/issues/712 and will close this issue.
