### ISSUE TITLE
provide support for "Projector Mode"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#342]
Discussed at 8/4/16 dev meeting...

Some sims have a "Projector Mode" option that is accessible via the PhET menu (Options submenu). Support for this (including a Property and query parameter) is currently duplicated in sim-specific code.  Investigate providing support for this in joist.

Before work on this is done, general handling of colors schemes in joist should be cleaned up, see #222.

**Comment by pixelzoom** [comment]
Standardizing on `colorProfile=projector` was done in https://github.com/phetsims/scenery-phet/issues/156).   And the ColorProfile is necessarily sim specific.  So the functionality that may be appropriate to add to joist is a way to add a "Projector Mode" item to the Options dialog (and handing of the associated i18n).   

Not on anyone's radar now, but let's leave this open.

**Comment by phet-steele** [comment]
@ariel-phet this would be great to have someone work on soon. Neglecting to do this has caused:

https://github.com/phetsims/states-of-matter/issues/206
https://github.com/phetsims/molecule-shapes/issues/148
https://github.com/phetsims/gravity-and-orbits/issues/262
https://github.com/phetsims/charges-and-fields/issues/119
https://github.com/phetsims/rutherford-scattering/issues/118

AND would have caused another issue for coulombs-law if @jessegreenberg and I didn't see this generalization issue. The copy/pasting of Projector Mode should likely stop.

To be a bit more specific about what should be moved, @pixelzoom noted in the comment above:

> So the functionality that may be appropriate to add to joist is a way to add a "Projector Mode" item to the Options dialog (and handing of the associated i18n).

As far as I know, this would involve simply moving the "Projector Mode" string into Joist and its associated Property. @pixelzoom could speak more to the work involved.

**Comment by pixelzoom** [comment]
Duplication of the "Projector Mode" string is the tip of the iceberg. Look at the current implementations (identified by @phet-steele above) and you'll see lots of code duplicated for creating the UI, almost certainly due to copy-paste. The only thing that's sim-specific about the Projector Mode feature is the associated color scheme. There's no reason why everything else (UI components, strings, wiring to PhET menu, ...) should not be in common code.

**Comment by pixelzoom** [comment]
Note also that sims with a Projector Mode are supposed to support `?colorProfile=projector`, for starting the sim in Projector Mode.  See initialize-globals.js.  Searching for `queryParameters.colorProfile` I see that only charges-and-fields supports it, and it appears to be unintentional omitted in the other sims.  So not having support in common code not only results in duplicate code, it results in inconsistent behavior.

**Comment by ariel-phet** [comment]
Marking for dev meeting, will see if we can get this fixed up in the various affected sims and be better going forward

**Comment by ariel-phet** [comment]
Since @jbphet is doing a re-release of SOM to fix up some other issues, tagging him on this issue as well.

**Comment by pixelzoom** [comment]
2/8/18 dev meeting notes:

• @ariel-phet clarified that he'd like @jbphet to investigate creating common-code support for the "Projector Mode" option, as well as supporting `?colorProfile=projector`, and using it in SOM.

• What probably needs to be migrated is the check box that's labeled "Projector Mode".  We do not want to migrate GlobalOptionsNode, that's the content for OptionsDialog that's provided by the client..

• General agreement that "Projector Mode" string will need to be re-translated when it's move to common code, we will not attempt to migrate translations.

**Comment by jbphet** [comment]
I'd like to discuss this a bit with other developers.  One possibility is to just create `ProjectorModeCheckbox.js` in joist, and have the clients use this as essentially a convenience type.  Another would be to go a step further and have a `GlobalOptionsNode` type in joist that has an option where a property can be provided such as `projectorModeProperty` and, if present, a checkbox to control it is created and added to the Sim instance's global options node.  If additional checkboxes or other controls are needed for setting sim options, the client could provide them in another option to `GlobalOptionNode` called something like 'additionalControls`.  This would be a bit less flexible than the current scheme, since we would need to choose a position for the Projector Mode check box within the options node (probably "always at the bottom" or "always at the top"), but this approach would get rid of a lot of duplicated code where sims are having to create their own GlobalOptionsNodes.  And, having the Projector Mode checkbox consistently positioned within the dialog would probably be a good idea for having a consistent UX between sims.

I spent a little time thinking about even fancier approaches where everything is handled via options provided to `Sim.js`, but wasn't enamored of any of my ideas.  Other devs might have some brainstorms here.

Assigning to @samreid and @pixelzoom to comment if they are available.  I'll also mark for dev meeting in the event that we haven't come to any good resolution by the next dev meeting.

**Comment by pixelzoom** [comment]
Having `ProjectorModeCheckbox.js` would be a sufficient first step.

**Comment by jbphet** [comment]
I polled @pixelzoom and @samreid about whether `ProjectorModeCheckbox.js` should go in joist or scenery-phet.  The strongest opinion on the matter was expressed by @samreid who said (over Slack), "It would be extremely odd for that string to be in scenery-phet".  I'm fine with that, so that'll be the plan.

**Comment by samreid** [comment]
Here's all of my comments in context:

John Blanco [10:53 AM]
Hey Sam, I saw you just unassigned from the common projector mode support issue.  Quick question about that: What's your opinion on where that should go?  I'm leaning towards scenery-phet, but one could argue that since it goes into a node that is the content of the options dialog, it should go into joist.  Chris was also thinking scenery-phet made the most sense, but we thought we should get your opinion.


Sam Reid [10:54 AM]
What’s the argument for scenery-phet?  Joist was my gut instinct, since that’s where it would be used.

John Blanco [11:01 AM]
It's a UI thing built on simpler, sun and scenery, subcomponents, somewhat like ThermometerNode and TimerNode.  Admittedly, those are a bit more elaborate than a checkbox, so I'd be fine saying that the ProjectorModeCheckbox is more part of the framework.  I want to move it to one place and leave it, though, since it has a string associated with it. (edited)

John Blanco [12:57 PM]
Any opinion on this (I think we both got caught up in other things)?

Sam Reid [12:58 PM]
It would be extremely odd for that string to be in scenery-phet.  I’m still leaning toward joist and hadn’t heard any good arguments against joist.

John Blanco [3:32 PM]
Okay, I'll go for joist.

**Comment by jbphet** [comment]
I went ahead and copied the existing translations of "Projector Mode" into the joist strings in the babel repo, mainly because I didn't want translations to lose this string.  I wrote a Node script to do this, and I'll ask the other devs and see if I should archive it in GitHub somewhere.

**Comment by jbphet** [comment]
Also, I did *not* remove the existing translations of "Projector Mode", since this would mess up the translation process.  It's possible to remove these from a sim's English and translated strings once it has been republished from master, but doing so before republication would cause problems.

**Comment by jbphet** [comment]
@pixelzoom - I've created the common checkbox for projector mode and integrated it into the States of Matter sims.  Can I get a quick review on this before I propagate to other sims?  I had to make a few decisions in the process of implementation, so I thought it'd be good to get your input.

**Comment by pixelzoom** [comment]
Looks good!  A couple of thoughts:

- Since this is new common code, should it be ES6?
- Consider adding options to `var label`'s font and maxWidth, in case this gets used outside of OptionsDialog.

**Comment by jbphet** [comment]
I've added options for the label font and the max text width.  I also converted to ES6 style, and confirmed that this is what we are currently doing (see https://github.com/phetsims/phet-info/issues/82#issuecomment-415539445).

**Comment by jbphet** [comment]
I've integrated this into all sims that were using projector mode.  In the process, I ended up getting rid of a couple of tandems (one in Charges and Fields, one in Coulomb's Law), and it makes me realize that this should probably have tandems added.  At this point in time, I'm not well versed in how to add phet-io support to common code components, so I'm assigning to @samreid to look at what's been done and add any phet-io code that is needed (or delegate as appropriate).

**Comment by jbphet** [comment]
For future reference, I tested this by verifying that the projector mode option was available and worked on all sims.  Since I transferred the translated strings into joist, I also spot checked a few locales on a single sim (Molecule Shapes) that had translations to verify that the translated string showed up, and tested a locale for which no translation existed and verified that the fallback to English worked.  This was done in RequireJS mode and on a built "all_phet_debug" version.

**Comment by samreid** [comment]
Since `ProjectorModeCheckbox extends Checkbox` it is already instrumented.  The steps we need to take are:
1) making sure clients pass it a tandem.
2) we likely will want to add `phetioInstanceDocumentation` to it
3) making sure the corresponding Property is instrumented.

I'll leave this assigned to me at medium priority and also assign @zepumph in case he gets to it first.

**Comment by jbphet** [comment]
@zepumph and @samreid - FYI - this is causing continuous test failures for charges-and-fields.

**Comment by zepumph** [comment]
I added the tandem and instance documentation.

**Comment by samreid** [comment]
I reviewed @zepumph's changes, and they look good. I also verified that the corresponding Property is instrumented.  @jbphet and @zepumph can this issue be closed?

**Comment by jbphet** [comment]
Coulomb's Law also had tandems in its global options node when I replaced its projector mode checkbox.  That sim isn't published, but perhaps it is being implemented with phet-io already in place.  Can you check on that one too?  Once that was is addressed (or we decide that there isn't a need), this can be closed.

**Comment by zepumph** [comment]
Thanks @jbphet I didn't realize it was so instrumented. I went ahead and added CL to the list of phet-io to catch this easier in the future. Closing.

**Comment by jbphet** [comment]
Coulomb's Law is failing CT, and the error message looks like it is related to this.  Here's the most recent error message as of this writing:

```
coulombs-law : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/Tandem.js?bust=1537224416897:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/axon/js/Property.js?bust=1537224416897:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/joist/js/Screen.js?bust=1537224416897:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/macro/CLMacroScreen.js?bust=1537224416897:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/coulombs-law-main.js?bust=1537224416897:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 4:28:48 PM
coulombs-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/Tandem.js?bust=1537224416897:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/axon/js/Property.js?bust=1537224416897:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/joist/js/Screen.js?bust=1537224416897:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/macro/CLMacroScreen.js?bust=1537224416897:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/coulombs-law-main.js?bust=1537224416897:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 4:28:48 PM
coulombs-law : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 9/17/2018, 4:28:48 
```

Reopening for @zepumph to have a look.

**Comment by zepumph** [comment]
See https://github.com/phetsims/coulombs-law/issues/67. I don't think these errors have to do with this issue. These errors are occurring because I added CL to more phet-io testing (which it is currently failing).

IMO it is better to have a sim that is partially outfitted with phet-io added to the phet-io list so that it can be maintained, rather than ignoring the sim and having it get more and more out of date.

**Comment by jbphet** [comment]
If this GitHub issue is unrelated to the CT failures, it's fine by me to close it.
