### ISSUE TITLE
AboutDialog is handled differently than OptionsDialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#422]
Right now in phetmenu, a new AboutDialog is created and shown every time the button is pressed. This works well for the way that Dialog.js works. Dialog.hide()` calls disposeDialog(), so hide() is really a dispose call. This doesn't really make sense, and it is confusing. So confusing that OptionsDialog is violating the assumption that hide === dispose. See here in PhetMenu:

```js
    // Define optionsDialog outside callbacks to avoid recreating
    var optionsDialog = null;

    /*
     * Description of the items in the menu. See Menu Item for a list of properties for each itemDescriptor
     */
    var itemDescriptors = [
      {
        text: menuItemOptionsString,
        present: !!sim.options.optionsNode,
        callback: function() {

          if ( !optionsDialog ) {
            optionsDialog = new OptionsDialog( sim.options.optionsNode, {
              tandem: tandem.createTandem( 'optionsDialog' )
            } );
          }

          optionsDialog.show();
        },
        tandem: tandem.createTandem( 'optionsMenuItem' ),
```
As seen this is complicated and not that intuitive, here is AboutDialog:

```js
callback: function() {
          var phetButton = sim.navigationBar.phetButton;
          new AboutDialog( sim.name, sim.version, sim.credits, Brand, sim.locale, phetButton, tandem.createTandem( 'aboutDialog' ) ).show();
        },
```

The options dialog implementation was causing a hidden bug when I instrumented an emitter in a pushButton, and it needed to be disposed correctly. 

I am going to change options dialog so that it is created new every time, but it seems like there is a bigger problem. Dialog's hide function is misleading, and should probably be changed. Here is a different stack trace representing the same problem.

```
curve-fitting
Uncaught Error: Assertion failed: This Node has already been disposed, and cannot be disposed again
Error: Assertion failed: This Node has already been disposed, and cannot be disposed again
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:21:13)
    at RectangularPushButton.Node.dispose (http://localhost/scenery/js/nodes/Node.js?bust=1495139239859:503:19)
    at ReducedChiSquaredStatisticDialog.Dialog.disposeDialog (http://localhost/joist/js/Dialog.js?bust=1495139239859:221:21)
    at ReducedChiSquaredStatisticDialog.hide (http://localhost/joist/js/Dialog.js?bust=1495139239859:267:14)
    at Object.fire (http://localhost/scenery-phet/js/BarrierRectangle.js?bust=1495139239859:48:57)
    at ButtonListener.setButtonState (http://localhost/scenery/js/input/ButtonListener.js?bust=1495139239859:129:31)
    at Object.up (http://localhost/scenery/js/input/ButtonListener.js?bust=1495139239859:87:14)
    at ButtonListener.buttonUp (http://localhost/scenery/js/input/DownUpListener.js?bust=1495139239859:123:22)
    at Object.up (http://localhost/scenery/js/input/DownUpListener.js?bust=1495139239859:56:16)
    at Input.dispatchToPointer (http://localhost/scenery/js/input/Input.js?bust=1495139239859:773:27)
```

**Comment by zepumph** [comment]
To be more specific about the curve-fitting, here is an image of how the Dialog is being is used, and I get an error if I dispose it again (close it twice).
![image](https://cloud.githubusercontent.com/assets/6856943/26222697/3edaad50-3bd8-11e7-8d0d-bcf4fe7473d7.png)

**Comment by zepumph** [comment]
So I went through and made it so that these dialogs are created new each time they are shown, and adapted the documentation. 75% of dialogs in the project were already doing this. 

I still think there needs to be more done with this issue though. To me there is a problem in having the `hide()` function call the `dispose()` function, especially with no documentation. I added documentation to Dialog.hide() but perhaps we should do more. @pixelzoom do you have insight about this, I think I remember getting Joist advice from you before. Please assign to someone else if they would have more insight.

**Comment by pixelzoom** [comment]
@zepumph said:
> To me there is a problem in having the `hide()` function call the `dispose()` function, especially with no documentation.

I agree, this is a problem. It make it impossible to hide/show one instance of a Dialog. It's also problematic if the client calls `dispose` directly while the Dialog is visible. `hide` and `dispose` should be decoupled, and clients should explicitly them explicitly (as applicable), and calling `dispose` on a visible dialog should probably fail an assertion.

**Comment by phet-steele** [comment]
@zepumph this fix does not quite work for phet-io. Here is what happens in charges-and-fields when attempting to open the options dialog twice:

```
Error: Assertion failed: Cannot register two different instances to the same id: chargesAndFields.navigationBar.phetButton.phetMenu.optionsDialog
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/assert/js/assert.js:21:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/phet-io/js/phetio.js?bust=1495221264795:414:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/phet-io/js/phetio.js?bust=1495221264795:57:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/tandem/js/Tandem.js?bust=1495221264795:128:36)
    at new OptionsDialog (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/joist/js/OptionsDialog.js?bust=1495221264795:46:16)
    at callback (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/joist/js/PhetMenu.js?bust=1495221264795:110:11)
    at Object.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/sun/js/MenuItem.js?bust=1495221264795:97:7)
    at ButtonListener.setButtonState (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/scenery/js/input/ButtonListener.js?bust=1495221264795:129:31)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/scenery/js/input/ButtonListener.js?bust=1495221264795:87:14)
    at ButtonListener.buttonUp (https://bayes.colorado.edu/continuous-testing/snapshot-1495220043722/scenery/js/input/DownUpListener.js?bust=1495221264795:123:22)
Approximately 5/19/2017, 12:54:03 PM
```

**Comment by zepumph** [comment]
I think that will fix it, I implemented hide in the optionsDialog that removedInstance on the tandem there. Thanks @phet-steele for the heads up. I don't have time to do this right now, but it seems like @pixelzoom agrees that it would be good to overhaul the way that Dialog.hide() and Dialog.dispose() works. We are going out of town for the next few weeks, but I will bring it up at dev meeting after we get back.

**Comment by zepumph** [comment]
#359 should include this overhaul for hide()/dispose(). Closing.
