### ISSUE TITLE
AboutDialog doesn't dispose its link texts

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#633]
When launching SOM in studio, this resulted in the following error:

```

Error: Assertion failed: phetioID already registered: statesOfMatter.general.view.navigationBar.phetButton.phetMenu.aboutDialogCapsule.aboutDialog.termsPrivacyAndLicensingLinkText.pickableProperty
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (http://localhost:8080/phet-io/js/phetioEngine.js:422:34)
    at Object.addPhetioObject (http://localhost:8080/phet-io/js/phetioEngine.js:604:49)
    at Tandem.addPhetioObject (http://localhost:8080/tandem/js/Tandem.js:156:38)
    at NodeProperty.initializePhetioObject (http://localhost:8080/tandem/js/PhetioObject.js:351:17)
    at new PhetioObject (http://localhost:8080/tandem/js/PhetioObject.js:187:10)
    at new Property (http://localhost:8080/axon/js/Property.js:68:5)
    at new NodeProperty (http://localhost:8080/scenery/js/util/NodeProperty.js:36:5)
    at new NodeIO (http://localhost:8080/scenery/js/nodes/NodeIO.js:25:30)
    at new RichTextIO (http://localhost:8080/scenery/js/nodes/RichTextIO.js:23:5)
```

Discovered while working on https://github.com/phetsims/states-of-matter/issues/287

**Comment by zepumph** [comment]
Implemented dispose above.
