### ISSUE TITLE
Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#661]
CT is showing

```
friction : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/studio/?sim=friction&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1600668440880%22%2C%22timestamp%22%3A1600670718880%7D
Uncaught Error: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
at PhetioCapsule.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/KeyboardHelpButton.js:57:38)
at PhetioCapsule.createArchetype (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/tandem/js/PhetioDynamicElementContainer.js:196:30)
at new PhetioDynamicElementContainer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/tandem/js/PhetioDynamicElementContainer.js:95:27)
at new PhetioCapsule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/tandem/js/PhetioCapsule.js:41:5)
at new KeyboardHelpButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/KeyboardHelpButton.js:56:39)
at new A11yButtonsHBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/A11yButtonsHBox.js:53:34)
at new NavigationBar (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/NavigationBar.js:158:26)
at new Sim (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/Sim.js:636:24)
at SimLauncher.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/friction/js/friction-main.js:49:3)
at Namespace.window.phet.joist.launchSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600668440880/joist/js/simLauncher.js:91:14)
id: Bayes Chrome
Snapshot from 9/21/2020, 12:07:20 AM
```

This looks like it was introduced in https://github.com/phetsims/joist/commit/64c4e5f716fa27eb59c4f3093c2dbfb932e45545 as part of https://github.com/phetsims/tasks/issues/1044

@pixelzoom can you please take a look?

**Comment by pixelzoom** [comment]
This is another ES6 conversion that was complicated by a11y, PhET-iO, and using `this` before calling super type constructor. I revert the conversion.  Someone else will have to convert this - I can't be spending this amount of time on a (what should be a simple) button.
