### ISSUE TITLE
Improve clickToDismissListener behavior with PanZoomListener

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#770]
From https://github.com/phetsims/circuit-construction-kit-common/issues/789 - clickToDismiss listener has problems with PanZoomListener.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/joist/commit/a096c520cbcca91ae8abebdefe14c35361c9290f I added a new listener to be used for click to dismiss.

An example usage is in CCK in https://github.com/phetsims/circuit-construction-kit-common/commit/c71117ff7bd2d2d68f104910ee5a903fb1e8170f. 

I also tested it out in build-a-molecule, ComboBox, CarouselComboBox, and energy-skate-park like this:

<details>
```patch
Index: energy-skate-park/js/common/view/ControlPointUI.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/energy-skate-park/js/common/view/ControlPointUI.js b/energy-skate-park/js/common/view/ControlPointUI.js
--- a/energy-skate-park/js/common/view/ControlPointUI.js	(revision 8b9c73ee530eb9ab21b52f2f765857140610bc3f)
+++ b/energy-skate-park/js/common/view/ControlPointUI.js	(date 1638833223621)
@@ -8,6 +8,7 @@
 
 import LinearFunction from '../../../../dot/js/LinearFunction.js';
 import Vector2 from '../../../../dot/js/Vector2.js';
+import DisplayClickToDismissListener from '../../../../joist/js/DisplayClickToDismissListener.js';
 import { Node } from '../../../../scenery/js/imports.js';
 import { Path } from '../../../../scenery/js/imports.js';
 import { Color } from '../../../../scenery/js/imports.js';
@@ -37,9 +38,7 @@
     // See ComboBox.js
     let enableClickToDismissListener = true;
 
-    // listener for 'click outside to dismiss'
-    this.clickToDismissListener = {
-      down: () => {
+    const dismissListener = () => {
         if ( enableClickToDismissListener ) {
           if ( _.indexOf( phet.joist.display.getInputListeners(), this.clickToDismissListener ) !== -1 ) {
             phet.joist.display.removeInputListener( this.clickToDismissListener );
@@ -52,8 +51,10 @@
           // to dismiss
           enableClickToDismissListener = true;
         }
-      }
     };
+
+    // listener for 'click outside to dismiss'
+    this.clickToDismissListener = new DisplayClickToDismissListener( dismissListener );
     phet.joist.display.addInputListener( this.clickToDismissListener );
 
     const isEndPoint = controlPointIndex === 0 || controlPointIndex === track.controlPoints.length - 1;
Index: sun/js/ComboBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/ComboBox.js b/sun/js/ComboBox.js
--- a/sun/js/ComboBox.js	(revision e7bf7bea865a781b7a8bff476b694aee8d1f25ad)
+++ b/sun/js/ComboBox.js	(date 1638834012940)
@@ -21,11 +21,10 @@
 import BooleanProperty from '../../axon/js/BooleanProperty.js';
 import dotRandom from '../../dot/js/dotRandom.js';
 import Vector2 from '../../dot/js/Vector2.js';
+import DisplayClickToDismissListener from '../../joist/js/DisplayClickToDismissListener.js';
 import InstanceRegistry from '../../phet-core/js/documentation/InstanceRegistry.js';
 import merge from '../../phet-core/js/merge.js';
-import { FocusManager } from '../../scenery/js/imports.js';
-import { PDOMPeer } from '../../scenery/js/imports.js';
-import { Node } from '../../scenery/js/imports.js';
+import { FocusManager, Node, PDOMPeer } from '../../scenery/js/imports.js';
 import generalCloseSoundPlayer from '../../tambo/js/shared-sound-players/generalCloseSoundPlayer.js';
 import generalOpenSoundPlayer from '../../tambo/js/shared-sound-players/generalOpenSoundPlayer.js';
 import EventType from '../../tandem/js/EventType.js';
@@ -223,22 +222,22 @@
     // @private the display that clickToDismissListener is added to, because the scene may change, see sun#14
     this.display = null;
 
-    // @private Clicking anywhere other than the button or list box will hide the list box.
-    this.clickToDismissListener = {
-      down: event => {
+    const dismissListener = event => {
 
-        // If fuzzing is enabled, exercise this listener some percentage of the time, so that this listener is tested.
-        // The rest of the time, ignore this listener, so that the listbox remains popped up, and we test making
-        // choices from the listbox. See https://github.com/phetsims/sun/issues/677
-        if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.25 ) {
+      // If fuzzing is enabled, exercise this listener some percentage of the time, so that this listener is tested.
+      // The rest of the time, ignore this listener, so that the listbox remains popped up, and we test making
+      // choices from the listbox. See https://github.com/phetsims/sun/issues/677
+      if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.25 ) {
 
-          // Ignore if we click over the button, since the button will handle hiding the list.
-          if ( !( event.trail.containsNode( this.button ) || event.trail.containsNode( this.listBox ) ) ) {
-            this.hideListBox();
-          }
+        // Ignore if we click over the button, since the button will handle hiding the list.
+        if ( !( event.trail.containsNode( this.button ) || event.trail.containsNode( this.listBox ) ) ) {
+          this.hideListBox();
         }
       }
     };
+
+    // @private Clicking anywhere other than the button or list box will hide the list box.
+    this.clickToDismissListener = new DisplayClickToDismissListener( dismissListener );
 
     // @private - (PDOM) when focus leaves the ComboBoxListBox, it should be closed. This could happen from keyboard
     // or from other screen reader controls (like VoiceOver gestures)
Index: sun/js/CarouselComboBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/CarouselComboBox.js b/sun/js/CarouselComboBox.js
--- a/sun/js/CarouselComboBox.js	(revision e7bf7bea865a781b7a8bff476b694aee8d1f25ad)
+++ b/sun/js/CarouselComboBox.js	(date 1638833888329)
@@ -24,16 +24,10 @@
 import Property from '../../axon/js/Property.js';
 import Dimension2 from '../../dot/js/Dimension2.js';
 import dotRandom from '../../dot/js/dotRandom.js';
+import DisplayClickToDismissListener from '../../joist/js/DisplayClickToDismissListener.js';
 import merge from '../../phet-core/js/merge.js';
 import AssertUtils from '../../phetcommon/js/AssertUtils.js';
-import { PressListener } from '../../scenery/js/imports.js';
-import { AlignBox } from '../../scenery/js/imports.js';
-import { AlignGroup } from '../../scenery/js/imports.js';
-import { HBox } from '../../scenery/js/imports.js';
-import { Node } from '../../scenery/js/imports.js';
-import { Rectangle } from '../../scenery/js/imports.js';
-import { VBox } from '../../scenery/js/imports.js';
-import { Color } from '../../scenery/js/imports.js';
+import { AlignBox, AlignGroup, Color, HBox, Node, PressListener, Rectangle, VBox } from '../../scenery/js/imports.js';
 import Tandem from '../../tandem/js/Tandem.js';
 import Carousel from './Carousel.js';
 import ComboBoxButton from './ComboBoxButton.js';
@@ -167,23 +161,23 @@
     const propertyListener = () => { carouselAndPageControl.visible = false; };
     property.link( propertyListener );
 
-    // Clicking outside this UI component will hide the carousel and page control.
-    // NOTE: adapted from ComboBox.
-    const clickToDismissListener = {
-      down: event => {
-        assert && assert( carousel.visible, 'this listener should be registered only when carousel is visible' );
+    const dismissListener = event => {
+      assert && assert( carousel.visible, 'this listener should be registered only when carousel is visible' );
 
-        // If fuzzing is enabled, exercise this listener some percentage of the time, so that this listener is tested.
-        // The rest of the time, ignore this listener, so that the carousel remains popped up, and we test making
-        // choices from the carousel. See https://github.com/phetsims/sun/issues/677
-        if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.25 ) {
-          const trail = event.trail;
-          if ( !trail.containsNode( button ) && !trail.containsNode( carousel ) && ( !pageControl || !trail.containsNode( pageControl ) ) ) {
-            carouselAndPageControl.visible = false;
-          }
+      // If fuzzing is enabled, exercise this listener some percentage of the time, so that this listener is tested.
+      // The rest of the time, ignore this listener, so that the carousel remains popped up, and we test making
+      // choices from the carousel. See https://github.com/phetsims/sun/issues/677
+      if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.25 ) {
+        const trail = event.trail;
+        if ( !trail.containsNode( button ) && !trail.containsNode( carousel ) && ( !pageControl || !trail.containsNode( pageControl ) ) ) {
+          carouselAndPageControl.visible = false;
         }
       }
     };
+
+    // Clicking outside this UI component will hide the carousel and page control.
+    // NOTE: adapted from ComboBox.
+    const clickToDismissListener = new DisplayClickToDismissListener( dismissListener );
 
     // Add clickToDismissListener only when the carousel & page control are visible. unlink is not needed.
     // NOTE: adapted from ComboBox.
Index: build-a-molecule/js/common/view/BAMScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build-a-molecule/js/common/view/BAMScreenView.js b/build-a-molecule/js/common/view/BAMScreenView.js
--- a/build-a-molecule/js/common/view/BAMScreenView.js	(revision c7d99fa44a10a805632d5b22f6dc60bc17eabd70)
+++ b/build-a-molecule/js/common/view/BAMScreenView.js	(date 1638832993033)
@@ -10,6 +10,7 @@
 
 import Property from '../../../../axon/js/Property.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
+import DisplayClickToDismissListener from '../../../../joist/js/DisplayClickToDismissListener.js';
 import ScreenView from '../../../../joist/js/ScreenView.js';
 import ThreeUtils from '../../../../mobius/js/ThreeUtils.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
@@ -21,8 +22,8 @@
 import KitPlayAreaNode from './KitPlayAreaNode.js';
 import MoleculeControlsHBox from './MoleculeControlsHBox.js';
 import RefillButton from './RefillButton.js';
-import WarningDialog from './WarningDialog.js';
 import Molecule3DDialog from './view3d/Molecule3DDialog.js';
+import WarningDialog from './WarningDialog.js';
 
 class BAMScreenView extends ScreenView {
   /**
@@ -263,12 +264,12 @@
       } );
     } );
 
-    // @private {function} listener for 'click outside to dismiss'
-    this.clickToDismissListener = {
-      down: () => {
-        bamModel.currentCollectionProperty.value.currentKitProperty.value.selectedAtomProperty.value = null;
-      }
+    const dismissListener = () => {
+      bamModel.currentCollectionProperty.value.currentKitProperty.value.selectedAtomProperty.value = null;
     };
+
+    // @private {function} listener for 'click outside to dismiss'
+    this.clickToDismissListener = new DisplayClickToDismissListener( dismissListener );
     phet.joist.display.addInputListener( this.clickToDismissListener );
 
     kitPanel.kitCarousel.pageNumberProperty.link( () => {


```
</details>

Before changing more places I think this should be reviewed.

**Comment by jessegreenberg** [comment]
In some local fuzzing I saw 
```
Error: Assertion failed: Attached listeners should be cleared before pointer disposal
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:25:13)
    at Touch.dispose (http://localhost:8080/chipper/dist/js/scenery/js/input/Pointer.js:457:15)
    at Input.removePointer (http://localhost:8080/chipper/dist/js/scenery/js/input/Input.js:1010:13)
    at Input.touchCancelAction.Action.phetioPlayback (http://localhost:8080/chipper/dist/js/scenery/js/input/Input.js:464:14)
    at Action.execute (http://localhost:8080/chipper/dist/js/axon/js/Action.js:195:18)
    at Input.touchCancel (http://localhost:8080/chipper/dist/js/scenery/js/input/Input.js:1342:28)
    at InputFuzzer.touchCancel (http://localhost:8080/chipper/dist/js/scenery/js/input/InputFuzzer.js:248:25)
    at InputFuzzer.touchCancelAction (http://localhost:8080/chipper/dist/js/scenery/js/input/InputFuzzer.js:59:12)
    at InputFuzzer.fuzzEvents (http://localhost:8080/chipper/dist/js/scenery/js/input/InputFuzzer.js:105:7)
    at SimDisplay.fuzzInputEvents (http://localhost:8080/chipper/dist/js/joist/js/SimDisplay.js:164:24)
```
because DisplayClickToDismissListener did not implement `interrupt` on the Pointer listener. This was fixed in the above commit.

**Comment by samreid** [comment]
I saw this in the latest CT column:

```
circuit-construction-kit-ac-virtual-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638849538574%22%2C%22timestamp%22%3A1638887531382%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/assert/js/assert.js:25:13)
at SimDisplay.removeInputListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/display/Display.js:1392:15)
at dismissListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/circuit-construction-kit-common/js/view/CircuitElementNode.js:226:30)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/joist/js/DisplayClickToDismissListener.js:25:9)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/input/Input.js:1988:23)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/input/Input.js:1942:10)
at Input.upEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/input/Input.js:1731:10)
at Input.mouseUpAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/input/Input.js:273:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/axon/js/Action.js:195:18)
at Input.mouseUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638849538574/chipper/dist/js/scenery/js/input/Input.js:1216:24)
id: Bayes Chrome
Snapshot from 12/6/2021, 8:58:58 PM
```

**Comment by jessegreenberg** [comment]
Thanks! I was able to see that locally with `brand=phet&ea&debugger&fuzz&fuzzPointers=2&screens=1&supportsPanAndZoom=false` - The DisplayClickToDismissListener was not getting disposed in the sim, causing this issue. After the above commit I am not seeing this error.

**Comment by samreid** [comment]
@jonathanolson was involved with developing the prior pattern, maybe it would be good to get his review of the proposed pattern?

**Comment by jessegreenberg** [comment]
@jonathanolson would you be able to review DisplayClickToDismissListener and its usage in circuit-construction-kit? See https://github.com/phetsims/circuit-construction-kit-common/issues/789 for an example of the problem this solves. I am proposing this is the new pattern for a "dismiss" listener. This listener factors out pointer interruption.

Feel free to pass back if you don't have time and Ill talk to management about getting someone else.

**Comment by jessegreenberg** [comment]
A problem with this listener was noted in https://github.com/phetsims/circuit-construction-kit-dc/issues/206 - @samreid identified the problem:

>The problem is that DisplayClickToDismissListener does not support more than one instance. For instance, testing on main for CCK-AC, neither screen 2 nor 3 can deselect circuit elements. However, if running any single screen with ?screens=2 or ?screens=3, it is fine.
DisplayClickToDismissListener is only used by Circuit Construction Kit, and attaches to pointer itself on press. Hence when there are 3 DisplayClickToDismissListeners, only the 1st one (for screen 1) attaches to the pointer. The others fail to attach because of this line:
https://github.com/phetsims/joist/blob/084b04e87cf07445a11a0c7915984617795ddad1/js/DisplayClickToDismissListener.ts#L59-L65

One solution could be to leverage scenery/DisplayedProperty. The listener could take an optional `targetNode` and only attach when the target is displayed.

**Comment by jessegreenberg** [comment]
That was done in the above commits, this is listener and the above fix is ready for review again.
