### ISSUE TITLE
Assertion failed: reentry detected, value=false, oldValue=true

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#782]
To reproduce, go to Ratio and Proportion, turn on voicing, and then click any readme button many times quickly. 

@jessegreenberg, I'm unsure if reentrancy is acceptable, or if we need to guard here. Over to you.

```
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
    at window.assertions.assertFunction (assert.js:25:13)
    at BooleanProperty._notifyListeners (Property.ts:286:15)
    at BooleanProperty.set (Property.ts:223:14)
    at VoicingToolbarItem.js? [sm]:185:30
    at TinyEmitter.emit (TinyEmitter.ts:93:9)
    at Emitter.ts:49:24
    at Emitter.execute (Action.ts:251:18)
    at Emitter.emit (Emitter.ts:70:19)
    at VoicingManager.handleSpeechSynthesisEnd (SpeechSynthesisAnnouncer.js? [sm]:413:29)
    at VoicingManager.cancelUtterance (SpeechSynthesisAnnouncer.js? [sm]:461:14)
```

**Comment by jessegreenberg** [comment]
Found the way to consistently produce this. Press a button twice quickly so that you play/stop before the synth begins to speak.

When you press the stop button this way there is no utterance to cancel yet so pressing it does nothing. Then the synth begins to speak from the "play" press a little later. Then the next time you press the button play again we hit this assertion because we are trying to cancel/play the same button which sets the same isPlayingProperty back and forth in the same callback.

**Comment by jessegreenberg** [comment]
I misdiagnosed, this is not caused by https://github.com/phetsims/utterance-queue/issues/66 but by https://github.com/phetsims/utterance-queue/issues/68 and has been fixed via that issue. UtteranceQueue.cancelUtterance did not remove the Utterance from the queue so pressing the "stop" button effectively did nothing if you pressed it before the Utterance made it to the Announcer.

@zepumph assigning to you to review/confirm if you wish otherwise I think this can be closed.

**Comment by zepumph** [comment]
Seems fixed to me! Thanks
