### ISSUE TITLE
CT: Assertion failed: phetioID already registered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#790]
Many sims complaining in CT intermittently about `navigationBar.phetButton.phetMenu.aboutDialogCapsule`, example below.   

Maybe related to https://github.com/phetsims/joist/commit/5b66d5c177a8059a910981aa1ddc1107dca61990? 

```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646705719978%22%2C%22timestamp%22%3A1646707353096%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: geometricOptics.general.view.navigationBar.keyboardHelpButton.keyboardHelpDialogCapsule.keyboardHelpDialog.closeButton.pressListener.pressAction.executedEmitter
Error: Assertion failed: phetioID already registered: geometricOptics.general.view.navigationBar.keyboardHelpButton.keyboardHelpDialogCapsule.keyboardHelpDialog.closeButton.pressListener.pressAction.executedEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/phet-io/js/phetioEngine.js:631:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/phet-io/js/phetioEngine.js:1122:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/tandem/js/Tandem.js:156:36)
at Emitter.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/tandem/js/PhetioObject.js:242:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/tandem/js/PhetioObject.js:107:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/tandem/js/PhetioDataHandler.js:62:5)
at new Emitter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/axon/js/Emitter.js:28:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/tandem/js/PhetioAction.js:48:28)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646705719978/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
id: Bayes Chrome
Snapshot from 3/7/2022, 7:15:19 PM
```

**Comment by zepumph** [comment]
Thanks. I forgot to dispose the Emitter in https://github.com/phetsims/phet-io/issues/1543.
