### ISSUE TITLE
CT: Assertion failed: reentry detected (VoicingToolbarItem)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#798]
Looks like this started appearing in CT on 3/16/2022, 1:18:58 AM, and has been appearing on every cycle since.  Entry point for the failure is `VoicingToolbarItem`. I don't see it in other sims.

```
john-travoltage : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647415138856%22%2C%22timestamp%22%3A1647416982933%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/assert/js/assert.js:25:13)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Property.js:225:15)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Property.js:156:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/joist/js/toolbar/VoicingToolbarItem.js:169:30
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Emitter.js:47:22)
at VoicingManager.handleSpeechSynthesisEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:433:29)
at SpeechSynthesisUtterance.endListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:395:12)
at VoicingManager.requestSpeech (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:420:21)
at VoicingManager.announce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:328:12)
id: Bayes Chrome
Snapshot from 3/16/2022, 1:18:58 AM
```

**Comment by jessegreenberg** [comment]
Good point, I think this is legitimate for the browser to do if it doesn't support or can't use SpeechSynthesis. OK if I make this Property `reentrant: true`? Done in the above commit with a comment.

**Comment by zepumph** [comment]
Really great stuff, good doc too.

**Comment by jessegreenberg** [comment]
OK thanks!
