### ISSUE TITLE
CT: PhET-iO API error: ... `keyboardHelpDialog.closeButton.enabledProperty`

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#816]
This type of issue is showing up in multiple sims in CT:
```
geometric-optics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/studio/?sim=geometric-optics&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654494561078%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
geometricOptics.general.view.navigationBar.keyboardHelpButton.keyboardHelpDialogCapsule.keyboardHelpDialog.closeButton.enabledProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:94:8)
at emit (Sim.ts:964:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM
```

**Comment by zepumph** [comment]
This has not been an issue on CT for quite some time, and I couldn't reproduce it just now. That said I can't find a commit that fixed it. We can reopen if it pops up again.
