### ISSUE TITLE
In phet-io brand: QueryParametersWarningDialog fails with Uncaught Error: Assertion failed: required tandems must be supplied

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#959]
Testing http://localhost/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&phetioStandalone&locales=*&keyboardLocaleSwitcher&ea&debugger&autoGenerateData=blorg 

I see:

```
assert.js:28 Uncaught Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (assert.js:28:13)
    at Emitter.initializePhetioObject (PhetioObject.ts:216:7)
    at new PhetioObject (PhetioObject.ts:196:12)
    at new PhetioDataHandler (PhetioDataHandler.ts:104:5)
    at new Emitter (Emitter.ts:47:5)
    at new PushButtonModel (PushButtonModel.ts:84:25)
    at new RectangularPushButton (RectangularPushButton.ts:50:29)
    at new CloseButton (CloseButton.ts:61:5)
    at new Dialog (Dialog.ts:242:25)
    at new OopsDialog (OopsDialog.ts:69:5)
```

@zepumph should this dialog be instrumented or OPT_OUT ed?

**Comment by zepumph** [comment]
Ahh very nice thanks. I tested on a built version and didn't see any trouble, so likely this is just a dev assertion, and doesn't effect any published versions (no MR needed). 

https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.22/phet-io/projectile-data-lab_all_phet-io.html?postMessageOnError&phetioStandalone&autoGenerateData=blorg

Anything else?

**Comment by samreid** [comment]
Excellent, works great in my testing. Thanks. Closing.
