### ISSUE TITLE
PhET-iO: Assertion when hiding all menu items

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#999]
All PhetMenu items have a featured visibleProperty that can be hidden. If all items in the menu are hidden, then the PhetMenu breaks with an assertion:

```
Error: Assertion failed: x must be a finite number: -Infinity
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:45:21)
    at assert (../../../../../kite/js/Shape.ts:218:14)
    at moveTo (../../../../../joist/js/PhetMenu.ts:332:5)
    at createBubbleShape (../../../../../joist/js/PhetMenu.ts:268:21)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/TinyStaticProperty.ts:56:9)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1570:30)
    at onAccessAttempt (../../../../../axon/js/TinyStaticProperty.ts:31:9)
    at get (../../../../../axon/js/TinyStaticProperty.ts:56:20)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1469:35)
    at onAccessAttempt (../../../../../axon/js/TinyStaticProperty.ts:31:9)
    at get (../../../../../axon/js/TinyStaticProperty.ts:56:20)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1923:33)
    at setLocalBounds (../../../../../../scenery/js/nodes/Node.ts:1878:9)
    at  (../../../../../../../scenery/js/layout/nodes/LayoutNode.ts:46:22)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:343:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:287:13)
```

Over in https://github.com/phetsims/studio/issues/256, @samreid and I are moving towards fixing any assertion that can occur from changing `phetioFeatured`  values in the sim.

This seems easy enough to fix, as I believe that the "About" dialog should never be hidable. There are multiple things that you can do instead if you are worried in the area: 1. set `allowLinks=false` via QP or the studio Property, 2. Toggle `navigationBar.phetButton.enabledProperty` off so you can't open the menu. 

I'll bring this up with @arouinfar when she gets back from vacation.

**Comment by arouinfar** [comment]
> This seems easy enough to fix, as I believe that the "About" dialog should never be hidable.  There are multiple things that you can do instead if you are worried in the area

I agree @zepumph. I don't see why the "About" menu option should be hidable given these other options.

**Comment by zepumph** [comment]
Ok perfect. I removed the visibleProperty from the about menu item, and updated migration processors. @samreid please review.

**Comment by samreid** [comment]
I agree with the decision and the implementation looks good. I tested at runtime in studio and the migration wrapper and all is well. Nice work, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
Good bot, thanks. I committed the change, @zepumph can you please spot check?
